import { type UserType } from '../utils/schemaValidation';

export const data: UserType[] = [
  {
    id: 1,
    fullName: 'Selie Colchett',
    email: 'scolchett0@msu.edu',
    gender: 'Female',
    active: false,
    createdAt: '12/18/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 2,
    fullName: 'Jada Casperri',
    email: 'jcasperri1@unblog.fr',
    gender: 'Female',
    active: false,
    createdAt: '12/26/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 3,
    fullName: 'Ariel Clayhill',
    email: 'aclayhill2@ebay.com',
    gender: 'Male',
    active: false,
    createdAt: '4/22/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 4,
    fullName: 'Kelsi Fluit',
    email: 'kfluit3@ocn.ne.jp',
    gender: 'Female',
    active: false,
    createdAt: '5/15/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 5,
    fullName: 'Marleen Divisek',
    email: 'mdivisek4@amazon.com',
    gender: 'Female',
    active: false,
    createdAt: '4/11/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 6,
    fullName: "Westleigh O'Keaveny",
    email: 'wokeaveny5@newsvine.com',
    gender: 'Male',
    active: false,
    createdAt: '1/29/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 7,
    fullName: 'Lucilia Elgood',
    email: 'lelgood6@wsj.com',
    gender: 'Female',
    active: true,
    createdAt: '7/1/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 8,
    fullName: 'Sherri Woltman',
    email: 'swoltman7@chron.com',
    gender: 'Female',
    active: false,
    createdAt: '2/27/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 9,
    fullName: 'Lita Stevani',
    email: 'lstevani8@cafepress.com',
    gender: 'Female',
    active: true,
    createdAt: '6/6/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 10,
    fullName: 'Ash Corbin',
    email: 'acorbin9@nydailynews.com',
    gender: 'Male',
    active: true,
    createdAt: '4/25/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 11,
    fullName: 'Shurlock Benediktsson',
    email: 'sbenediktssona@discovery.com',
    gender: 'Male',
    active: true,
    createdAt: '5/23/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 12,
    fullName: 'Bayard Wilmington',
    email: 'bwilmingtonb@wufoo.com',
    gender: 'Male',
    active: false,
    createdAt: '6/14/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 13,
    fullName: 'Leland Menichini',
    email: 'lmenichinic@phoca.cz',
    gender: 'Male',
    active: false,
    createdAt: '1/25/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 14,
    fullName: 'Scottie Dicty',
    email: 'sdictyd@weather.com',
    gender: 'Male',
    active: false,
    createdAt: '11/23/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 15,
    fullName: 'Abrahan Oxbury',
    email: 'aoxburye@aol.com',
    gender: 'Male',
    active: true,
    createdAt: '10/5/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 16,
    fullName: 'Ahmed Archbold',
    email: 'aarchboldf@walmart.com',
    gender: 'Male',
    active: false,
    createdAt: '7/28/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 17,
    fullName: 'Wilhelmine Lante',
    email: 'wlanteg@tripod.com',
    gender: 'Female',
    active: true,
    createdAt: '10/13/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 18,
    fullName: 'Bellanca Wemyss',
    email: 'bwemyssh@cbslocal.com',
    gender: 'Female',
    active: true,
    createdAt: '8/15/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 19,
    fullName: 'Kellen Farquar',
    email: 'kfarquari@hexun.com',
    gender: 'Male',
    active: false,
    createdAt: '8/1/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 20,
    fullName: 'Karola Kidder',
    email: 'kkidderj@mediafire.com',
    gender: 'Female',
    active: false,
    createdAt: '4/5/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 21,
    fullName: 'Xever Hebbes',
    email: 'xhebbesk@arizona.edu',
    gender: 'Male',
    active: false,
    createdAt: '5/8/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 22,
    fullName: 'Angela Colbeck',
    email: 'acolbeckl@ftc.gov',
    gender: 'Female',
    active: true,
    createdAt: '4/2/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 23,
    fullName: 'Neel Windross',
    email: 'nwindrossm@wisc.edu',
    gender: 'Male',
    active: true,
    createdAt: '2/13/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 24,
    fullName: 'Marion Middlemiss',
    email: 'mmiddlemissn@google.pl',
    gender: 'Female',
    active: true,
    createdAt: '3/28/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 25,
    fullName: 'Delbert Prescott',
    email: 'dprescotto@ehow.com',
    gender: 'Male',
    active: true,
    createdAt: '11/20/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 26,
    fullName: 'Roley Chapleo',
    email: 'rchapleop@nps.gov',
    gender: 'Male',
    active: true,
    createdAt: '7/18/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 27,
    fullName: 'Elwyn Le Cornu',
    email: 'eleq@friendfeed.com',
    gender: 'Male',
    active: true,
    createdAt: '8/10/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 28,
    fullName: 'Ruy Tommis',
    email: 'rtommisr@fema.gov',
    gender: 'Male',
    active: true,
    createdAt: '2/6/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 29,
    fullName: 'Isa Fewless',
    email: 'ifewlesss@free.fr',
    gender: 'Female',
    active: false,
    createdAt: '11/30/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 30,
    fullName: 'Norrie Timlett',
    email: 'ntimlettt@princeton.edu',
    gender: 'Male',
    active: true,
    createdAt: '8/14/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 31,
    fullName: 'Vincent Abramson',
    email: 'vabramsonu@vinaora.com',
    gender: 'Male',
    active: false,
    createdAt: '10/16/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 32,
    fullName: 'Barney Thomassin',
    email: 'bthomassinv@indiatimes.com',
    gender: 'Male',
    active: true,
    createdAt: '10/1/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 33,
    fullName: 'Kira Skippon',
    email: 'kskipponw@wired.com',
    gender: 'Female',
    active: true,
    createdAt: '10/22/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 34,
    fullName: 'Vernen Penhale',
    email: 'vpenhalex@ycombinator.com',
    gender: 'Male',
    active: false,
    createdAt: '3/10/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 35,
    fullName: 'Margi Britee',
    email: 'mbriteey@google.co.uk',
    gender: 'Female',
    active: true,
    createdAt: '4/4/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 36,
    fullName: 'Eamon Brame',
    email: 'ebramez@mapy.cz',
    gender: 'Male',
    active: true,
    createdAt: '5/2/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 37,
    fullName: 'Denver McIlveen',
    email: 'dmcilveen10@uiuc.edu',
    gender: 'Male',
    active: true,
    createdAt: '2/14/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 38,
    fullName: 'Rosmunda Immer',
    email: 'rimmer11@wunderground.com',
    gender: 'Female',
    active: false,
    createdAt: '2/16/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 39,
    fullName: 'Tomasine Gors',
    email: 'tgors12@howstuffworks.com',
    gender: 'Female',
    active: true,
    createdAt: '1/3/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 40,
    fullName: 'Adelind Demschke',
    email: 'ademschke13@apache.org',
    gender: 'Female',
    active: true,
    createdAt: '12/21/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 41,
    fullName: 'Arlinda Yurukhin',
    email: 'ayurukhin14@gov.uk',
    gender: 'Female',
    active: false,
    createdAt: '11/11/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 42,
    fullName: 'Tildie Philo',
    email: 'tphilo15@ibm.com',
    gender: 'Female',
    active: false,
    createdAt: '2/19/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 43,
    fullName: 'Janette Grainge',
    email: 'jgrainge16@irs.gov',
    gender: 'Female',
    active: false,
    createdAt: '5/17/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 44,
    fullName: "Louie O'Neal",
    email: 'loneal17@about.me',
    gender: 'Male',
    active: false,
    createdAt: '9/1/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 45,
    fullName: 'Cort Pheasant',
    email: 'cpheasant18@howstuffworks.com',
    gender: 'Male',
    active: false,
    createdAt: '11/24/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 46,
    fullName: 'Egon Haddeston',
    email: 'ehaddeston19@comsenz.com',
    gender: 'Male',
    active: false,
    createdAt: '11/19/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 47,
    fullName: 'Dino Sirmond',
    email: 'dsirmond1a@cargocollective.com',
    gender: 'Male',
    active: false,
    createdAt: '5/24/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 48,
    fullName: 'Yoshiko Quarrington',
    email: 'yquarrington1b@npr.org',
    gender: 'Female',
    active: true,
    createdAt: '9/13/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 49,
    fullName: 'Auroora Frances',
    email: 'afrances1c@salon.com',
    gender: 'Female',
    active: false,
    createdAt: '9/23/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 50,
    fullName: 'Maire Lober',
    email: 'mlober1d@spotify.com',
    gender: 'Female',
    active: false,
    createdAt: '9/16/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 51,
    fullName: 'Murdock Swabey',
    email: 'mswabey1e@naver.com',
    gender: 'Male',
    active: true,
    createdAt: '3/25/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 52,
    fullName: 'Joan Rival',
    email: 'jrival1f@dion.ne.jp',
    gender: 'Female',
    active: true,
    createdAt: '12/9/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 53,
    fullName: 'Kriste Pechan',
    email: 'kpechan1g@nifty.com',
    gender: 'Female',
    active: false,
    createdAt: '12/17/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 54,
    fullName: 'Raviv Lakin',
    email: 'rlakin1h@netlog.com',
    gender: 'Male',
    active: true,
    createdAt: '11/17/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 55,
    fullName: 'Adrian Gillard',
    email: 'agillard1i@cbslocal.com',
    gender: 'Male',
    active: true,
    createdAt: '1/10/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 56,
    fullName: 'Morgen Mossman',
    email: 'mmossman1j@bluehost.com',
    gender: 'Female',
    active: false,
    createdAt: '9/2/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 57,
    fullName: 'Payton Oxenden',
    email: 'poxenden1k@hubpages.com',
    gender: 'Male',
    active: false,
    createdAt: '1/27/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 58,
    fullName: 'Bentlee Secretan',
    email: 'bsecretan1l@printfriendly.com',
    gender: 'Male',
    active: true,
    createdAt: '7/27/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 59,
    fullName: 'Winnie Sarjent',
    email: 'wsarjent1m@tamu.edu',
    gender: 'Female',
    active: false,
    createdAt: '8/1/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 60,
    fullName: 'Fons Briston',
    email: 'fbriston1n@hatena.ne.jp',
    gender: 'Male',
    active: false,
    createdAt: '9/18/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 61,
    fullName: 'Hildy Bramall',
    email: 'hbramall1o@techcrunch.com',
    gender: 'Female',
    active: true,
    createdAt: '5/8/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 62,
    fullName: 'Maritsa Kacheller',
    email: 'mkacheller1p@washingtonpost.com',
    gender: 'Female',
    active: true,
    createdAt: '8/31/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 63,
    fullName: 'Crystie Woodsford',
    email: 'cwoodsford1q@msu.edu',
    gender: 'Female',
    active: false,
    createdAt: '11/18/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 64,
    fullName: 'Jocko Snarr',
    email: 'jsnarr1r@shop-pro.jp',
    gender: 'Male',
    active: true,
    createdAt: '9/26/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 65,
    fullName: 'Mitchael Gillivrie',
    email: 'mgillivrie1s@census.gov',
    gender: 'Male',
    active: false,
    createdAt: '8/10/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 66,
    fullName: 'Northrop Giblett',
    email: 'ngiblett1t@uiuc.edu',
    gender: 'Male',
    active: false,
    createdAt: '10/11/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 67,
    fullName: 'Mariellen Davidovsky',
    email: 'mdavidovsky1u@cbslocal.com',
    gender: 'Female',
    active: false,
    createdAt: '9/11/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 68,
    fullName: 'Eduard Coules',
    email: 'ecoules1v@wufoo.com',
    gender: 'Male',
    active: false,
    createdAt: '2/20/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 69,
    fullName: 'Jilli Pasticznyk',
    email: 'jpasticznyk1w@webnode.com',
    gender: 'Female',
    active: false,
    createdAt: '11/21/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 70,
    fullName: 'Shanon Gollin',
    email: 'sgollin1x@squarespace.com',
    gender: 'Female',
    active: false,
    createdAt: '1/18/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 71,
    fullName: 'Stanwood Denniston',
    email: 'sdenniston1y@google.cn',
    gender: 'Male',
    active: true,
    createdAt: '10/23/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 72,
    fullName: 'Blanch Dearman',
    email: 'bdearman1z@state.gov',
    gender: 'Female',
    active: true,
    createdAt: '10/9/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 73,
    fullName: 'Zedekiah Thackwray',
    email: 'zthackwray20@angelfire.com',
    gender: 'Male',
    active: false,
    createdAt: '11/2/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 74,
    fullName: 'Vickie Stebbings',
    email: 'vstebbings21@so-net.ne.jp',
    gender: 'Female',
    active: true,
    createdAt: '5/16/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 75,
    fullName: 'Dewie Le Gall',
    email: 'dle22@meetup.com',
    gender: 'Male',
    active: true,
    createdAt: '8/21/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 76,
    fullName: 'Lew Sawford',
    email: 'lsawford23@netscape.com',
    gender: 'Male',
    active: false,
    createdAt: '8/30/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 77,
    fullName: 'Collete Grimes',
    email: 'cgrimes24@webnode.com',
    gender: 'Female',
    active: false,
    createdAt: '10/24/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 78,
    fullName: 'Elsie Kinnach',
    email: 'ekinnach25@slideshare.net',
    gender: 'Female',
    active: true,
    createdAt: '10/28/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 79,
    fullName: 'Jewel Courtin',
    email: 'jcourtin26@census.gov',
    gender: 'Female',
    active: true,
    createdAt: '8/18/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 80,
    fullName: 'Shayna Carlisle',
    email: 'scarlisle27@slideshare.net',
    gender: 'Female',
    active: true,
    createdAt: '11/1/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 81,
    fullName: 'Torrin Humpherston',
    email: 'thumpherston28@newsvine.com',
    gender: 'Male',
    active: true,
    createdAt: '6/21/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 82,
    fullName: 'Veronike Netley',
    email: 'vnetley29@wunderground.com',
    gender: 'Female',
    active: false,
    createdAt: '12/7/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 83,
    fullName: 'Carney Treherne',
    email: 'ctreherne2a@cafepress.com',
    gender: 'Male',
    active: true,
    createdAt: '8/18/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 84,
    fullName: 'Sergei Croxford',
    email: 'scroxford2b@sitemeter.com',
    gender: 'Male',
    active: true,
    createdAt: '1/8/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 85,
    fullName: 'Georgeanne Bawme',
    email: 'gbawme2c@squarespace.com',
    gender: 'Female',
    active: false,
    createdAt: '2/27/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 86,
    fullName: 'Casey Aucourte',
    email: 'caucourte2d@utexas.edu',
    gender: 'Male',
    active: true,
    createdAt: '9/10/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 87,
    fullName: 'Tremain Mendonca',
    email: 'tmendonca2e@oakley.com',
    gender: 'Male',
    active: false,
    createdAt: '5/7/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 88,
    fullName: 'Miguel Arnaut',
    email: 'marnaut2f@nydailynews.com',
    gender: 'Male',
    active: false,
    createdAt: '6/11/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 89,
    fullName: 'Courtney Sadlier',
    email: 'csadlier2g@vimeo.com',
    gender: 'Female',
    active: false,
    createdAt: '6/25/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 90,
    fullName: 'Wallie Parkey',
    email: 'wparkey2h@google.co.uk',
    gender: 'Male',
    active: true,
    createdAt: '7/6/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 91,
    fullName: 'Craggy Bernolet',
    email: 'cbernolet2i@sogou.com',
    gender: 'Male',
    active: true,
    createdAt: '10/8/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 92,
    fullName: 'Ignace Wattins',
    email: 'iwattins2j@sina.com.cn',
    gender: 'Male',
    active: true,
    createdAt: '9/23/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 93,
    fullName: 'Cyrus Baldery',
    email: 'cbaldery2k@businessinsider.com',
    gender: 'Male',
    active: true,
    createdAt: '11/8/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 94,
    fullName: 'Viviana Sherman',
    email: 'vsherman2l@themeforest.net',
    gender: 'Female',
    active: true,
    createdAt: '9/21/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 95,
    fullName: 'Roseline Pattillo',
    email: 'rpattillo2m@sbwire.com',
    gender: 'Female',
    active: true,
    createdAt: '1/26/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 96,
    fullName: 'Genny Keal',
    email: 'gkeal2n@archive.org',
    gender: 'Female',
    active: false,
    createdAt: '12/3/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 97,
    fullName: 'Miriam Inmett',
    email: 'minmett2o@imdb.com',
    gender: 'Female',
    active: false,
    createdAt: '11/12/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 98,
    fullName: 'Carol Ceschelli',
    email: 'cceschelli2p@github.io',
    gender: 'Female',
    active: false,
    createdAt: '1/15/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 99,
    fullName: 'Herta Pfeffer',
    email: 'hpfeffer2q@ebay.com',
    gender: 'Female',
    active: false,
    createdAt: '3/11/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 100,
    fullName: 'Lavina Ricciardi',
    email: 'lricciardi2r@buzzfeed.com',
    gender: 'Female',
    active: true,
    createdAt: '12/24/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 101,
    fullName: 'Miguelita Dunsmore',
    email: 'mdunsmore2s@statcounter.com',
    gender: 'Female',
    active: false,
    createdAt: '9/26/2022',
    age: Math.floor(Math.random() * 100),
  },
];
