import { UserType } from './components/Form';

export const data: UserType[] = [
  {
    id: 1,
    fullName: 'Bartel Slatcher',
    email: 'bslatcher0@ted.com',
    createdAt: '4/23/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 2,
    fullName: 'Brigg Choak',
    email: 'bchoak1@amazon.com',
    createdAt: '11/7/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 3,
    fullName: 'Malanie Fearnley',
    email: 'mfearnley2@google.de',
    createdAt: '7/30/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 4,
    fullName: 'Jacintha Algeo',
    email: 'jalgeo3@discuz.net',
    createdAt: '6/15/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 5,
    fullName: 'Omero Befroy',
    email: 'obefroy4@opera.com',
    createdAt: '4/28/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 6,
    fullName: 'Malanie Osgar',
    email: 'mosgar5@dagondesign.com',
    createdAt: '4/11/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 7,
    fullName: 'Maura Jagoe',
    email: 'mjagoe6@myspace.com',
    createdAt: '3/20/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 8,
    fullName: 'Lorenzo Midford',
    email: 'lmidford7@wsj.com',
    createdAt: '4/17/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 9,
    fullName: 'Evyn Shimmans',
    email: 'eshimmans8@scientificamerican.com',
    createdAt: '6/3/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 10,
    fullName: 'Kirby Bartol',
    email: 'kbartol9@hp.com',
    createdAt: '2/16/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 11,
    fullName: 'Jaquelin Caldayrou',
    email: 'jcaldayroua@netscape.com',
    createdAt: '10/28/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 12,
    fullName: 'Bond Crowdace',
    email: 'bcrowdaceb@abc.net.au',
    createdAt: '6/17/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 13,
    fullName: 'Madel Malling',
    email: 'mmallingc@squidoo.com',
    createdAt: '2/20/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 14,
    fullName: 'Goldarina Bodemeaid',
    email: 'gbodemeaidd@wordpress.org',
    createdAt: '9/8/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 15,
    fullName: 'Saul Weson',
    email: 'swesone@gmpg.org',
    createdAt: '10/27/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 16,
    fullName: 'Trip Berzen',
    email: 'tberzenf@zimbio.com',
    createdAt: '3/18/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 17,
    fullName: 'Rosene Hemmingway',
    email: 'rhemmingwayg@redcross.org',
    createdAt: '2/28/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 18,
    fullName: 'Emlen Saunt',
    email: 'esaunth@nsw.gov.au',
    createdAt: '3/29/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 19,
    fullName: 'Lottie Agnolo',
    email: 'lagnoloi@ycombinator.com',
    createdAt: '6/18/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 20,
    fullName: 'Maggee Cosely',
    email: 'mcoselyj@census.gov',
    createdAt: '7/31/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 21,
    fullName: 'Clotilda Tolwood',
    email: 'ctolwoodk@mlb.com',
    createdAt: '11/26/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 22,
    fullName: 'Pru Pawelek',
    email: 'ppawelekl@dell.com',
    createdAt: '1/31/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 23,
    fullName: 'Trudi Likly',
    email: 'tliklym@ucsd.edu',
    createdAt: '12/1/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 24,
    fullName: 'Jenna Abbatucci',
    email: 'jabbatuccin@vinaora.com',
    createdAt: '6/4/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 25,
    fullName: 'Galven Dethloff',
    email: 'gdethloffo@nasa.gov',
    createdAt: '7/21/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 26,
    fullName: 'Dori Elsay',
    email: 'delsayp@jimdo.com',
    createdAt: '5/24/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 27,
    fullName: 'Frannie Winspire',
    email: 'fwinspireq@cnet.com',
    createdAt: '1/13/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 28,
    fullName: 'Tully Pape',
    email: 'tpaper@netlog.com',
    createdAt: '11/5/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 29,
    fullName: 'Berne Bailles',
    email: 'bbailless@tmall.com',
    createdAt: '3/17/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 30,
    fullName: 'Taryn Cloake',
    email: 'tcloaket@ehow.com',
    createdAt: '1/11/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 31,
    fullName: 'Hughie Mullan',
    email: 'hmullanu@hexun.com',
    createdAt: '10/3/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 32,
    fullName: 'Carrissa Huntriss',
    email: 'chuntrissv@google.es',
    createdAt: '11/5/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 33,
    fullName: 'Aridatha Keming',
    email: 'akemingw@reverbnation.com',
    createdAt: '3/4/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 34,
    fullName: 'Alford Stambridge',
    email: 'astambridgex@list-manage.com',
    createdAt: '8/26/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 35,
    fullName: 'Jewell Maccari',
    email: 'jmaccariy@goo.gl',
    createdAt: '5/9/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 36,
    fullName: 'Delora Brydell',
    email: 'dbrydellz@skyrock.com',
    createdAt: '12/25/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 37,
    fullName: 'Cleveland Brugman',
    email: 'cbrugman10@patch.com',
    createdAt: '11/29/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 38,
    fullName: 'Inness Mander',
    email: 'imander11@shop-pro.jp',
    createdAt: '5/26/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 39,
    fullName: 'Brooke Le land',
    email: 'ble12@people.com.cn',
    createdAt: '10/19/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 40,
    fullName: 'Gina Lawly',
    email: 'glawly13@github.io',
    createdAt: '7/30/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 41,
    fullName: 'Frank Vlasov',
    email: 'fvlasov14@cornell.edu',
    createdAt: '11/22/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 42,
    fullName: 'Richart Klass',
    email: 'rklass15@vk.com',
    createdAt: '3/22/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 43,
    fullName: 'Kathryn Janew',
    email: 'kjanew16@utexas.edu',
    createdAt: '4/16/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 44,
    fullName: 'Corabella Edmonston',
    email: 'cedmonston17@google.it',
    createdAt: '12/25/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 45,
    fullName: 'Charmane Vella',
    email: 'cvella18@timesonline.co.uk',
    createdAt: '12/7/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 46,
    fullName: 'Brande Barsham',
    email: 'bbarsham19@google.es',
    createdAt: '4/2/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 47,
    fullName: 'Tabb Sumsion',
    email: 'tsumsion1a@cdbaby.com',
    createdAt: '7/3/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 48,
    fullName: 'Chere Union',
    email: 'cunion1b@plala.or.jp',
    createdAt: '4/17/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 49,
    fullName: 'Lita Jablonski',
    email: 'ljablonski1c@rediff.com',
    createdAt: '3/25/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 50,
    fullName: 'Justino Kohler',
    email: 'jkohler1d@livejournal.com',
    createdAt: '2/14/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 51,
    fullName: 'Corinne Hancke',
    email: 'chancke1e@microsoft.com',
    createdAt: '8/25/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 52,
    fullName: 'Cristal Deacock',
    email: 'cdeacock1f@google.es',
    createdAt: '4/23/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 53,
    fullName: 'Wheeler Pullan',
    email: 'wpullan1g@cpanel.net',
    createdAt: '4/21/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 54,
    fullName: 'Delainey Coles',
    email: 'dcoles1h@usda.gov',
    createdAt: '7/11/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 55,
    fullName: 'Mack Christopherson',
    email: 'mchristopherson1i@biblegateway.com',
    createdAt: '7/2/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 56,
    fullName: 'Ulrika Guidera',
    email: 'uguidera1j@rediff.com',
    createdAt: '9/22/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 57,
    fullName: 'Laurence Tondeur',
    email: 'ltondeur1k@google.com.hk',
    createdAt: '1/31/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 58,
    fullName: "Dionne O'Kenny",
    email: 'dokenny1l@multiply.com',
    createdAt: '6/20/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 59,
    fullName: 'Feliks Coolican',
    email: 'fcoolican1m@wufoo.com',
    createdAt: '2/5/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 60,
    fullName: 'Aurthur Dowdam',
    email: 'adowdam1n@theguardian.com',
    createdAt: '11/29/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 61,
    fullName: 'Lilly Belin',
    email: 'lbelin1o@typepad.com',
    createdAt: '9/23/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 62,
    fullName: 'Merrily Sifleet',
    email: 'msifleet1p@blogspot.com',
    createdAt: '12/21/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 63,
    fullName: 'Sondra Shillinglaw',
    email: 'sshillinglaw1q@privacy.gov.au',
    createdAt: '2/28/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 64,
    fullName: 'Luella Lindbergh',
    email: 'llindbergh1r@imageshack.us',
    createdAt: '10/28/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 65,
    fullName: 'Patsy Harpin',
    email: 'pharpin1s@indiegogo.com',
    createdAt: '11/22/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 66,
    fullName: 'Enos Rendle',
    email: 'erendle1t@illinois.edu',
    createdAt: '11/23/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 67,
    fullName: 'Effie Wiffill',
    email: 'ewiffill1u@cnbc.com',
    createdAt: '10/30/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 68,
    fullName: 'Sylvan Ashwin',
    email: 'sashwin1v@geocities.jp',
    createdAt: '11/20/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 69,
    fullName: 'Gisele Balsom',
    email: 'gbalsom1w@desdev.cn',
    createdAt: '8/29/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 70,
    fullName: 'Bearnard Lowater',
    email: 'blowater1x@sakura.ne.jp',
    createdAt: '12/7/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 71,
    fullName: 'Kevyn Geraudy',
    email: 'kgeraudy1y@techcrunch.com',
    createdAt: '3/19/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 72,
    fullName: 'Theodor Beininck',
    email: 'tbeininck1z@cafepress.com',
    createdAt: '9/9/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 73,
    fullName: 'Gayler Marsters',
    email: 'gmarsters20@webmd.com',
    createdAt: '10/16/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 74,
    fullName: 'Marcelle Chatelain',
    email: 'mchatelain21@walmart.com',
    createdAt: '8/13/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 75,
    fullName: 'Delly Huddart',
    email: 'dhuddart22@51.la',
    createdAt: '2/26/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 76,
    fullName: 'Linell Huegett',
    email: 'lhuegett23@phoca.cz',
    createdAt: '8/30/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 77,
    fullName: 'Dorice MacKessock',
    email: 'dmackessock24@stanford.edu',
    createdAt: '10/15/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 78,
    fullName: 'Salvador Rousell',
    email: 'srousell25@nytimes.com',
    createdAt: '11/9/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 79,
    fullName: 'Savina Wyllcock',
    email: 'swyllcock26@g.co',
    createdAt: '11/2/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 80,
    fullName: 'Tallou Penreth',
    email: 'tpenreth27@g.co',
    createdAt: '3/27/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 81,
    fullName: 'Katerine Bownas',
    email: 'kbownas28@alibaba.com',
    createdAt: '4/11/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 82,
    fullName: 'Mindy Barber',
    email: 'mbarber29@abc.net.au',
    createdAt: '4/22/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 83,
    fullName: 'Odey Mongain',
    email: 'omongain2a@marriott.com',
    createdAt: '10/23/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 84,
    fullName: 'Rawley Stubbley',
    email: 'rstubbley2b@posterous.com',
    createdAt: '2/7/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 85,
    fullName: 'Cecil Versey',
    email: 'cversey2c@goodreads.com',
    createdAt: '3/5/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 86,
    fullName: 'Athene Sanbrooke',
    email: 'asanbrooke2d@wiley.com',
    createdAt: '4/19/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 87,
    fullName: 'Illa Andryushchenko',
    email: 'iandryushchenko2e@cyberchimps.com',
    createdAt: '7/23/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 88,
    fullName: 'Jeno Pughsley',
    email: 'jpughsley2f@state.gov',
    createdAt: '10/27/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 89,
    fullName: 'Jillene Canape',
    email: 'jcanape2g@storify.com',
    createdAt: '3/7/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 90,
    fullName: 'Evelina Garrit',
    email: 'egarrit2h@cdbaby.com',
    createdAt: '2/15/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 91,
    fullName: 'Ceciley Pepperd',
    email: 'cpepperd2i@tripadvisor.com',
    createdAt: '5/3/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 92,
    fullName: 'Brooke Schooling',
    email: 'bschooling2j@360.cn',
    createdAt: '4/13/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 93,
    fullName: 'Kayle Gotcher',
    email: 'kgotcher2k@gravatar.com',
    createdAt: '10/21/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 94,
    fullName: 'Herschel Ottewell',
    email: 'hottewell2l@kickstarter.com',
    createdAt: '12/9/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 95,
    fullName: 'Jefferey Hamblyn',
    email: 'jhamblyn2m@gizmodo.com',
    createdAt: '2/13/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 96,
    fullName: 'Temp Rosenblad',
    email: 'trosenblad2n@livejournal.com',
    createdAt: '9/23/2022',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 97,
    fullName: 'Sutherlan Evershed',
    email: 'severshed2o@shop-pro.jp',
    createdAt: '3/3/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 98,
    fullName: 'Ned Chewter',
    email: 'nchewter2p@narod.ru',
    createdAt: '8/24/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 99,
    fullName: 'Bjorn Daborn',
    email: 'bdaborn2q@archive.org',
    createdAt: '1/9/2023',
    age: Math.floor(Math.random() * 100),
  },
  {
    id: 100,
    fullName: 'Anne Vernau',
    email: 'avernau2r@shinystat.com',
    createdAt: '11/2/2022',
    age: Math.floor(Math.random() * 100),
  },
];
